%YAML 1.2
---
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera:
  fx: 520.908620
  fy: 521.007327
  cx: 325.141442
  cy: 249.701764
  k1: 0.231222
  k2: -0.784899
  p1: -0.003257
  p2: -0.000105
  k3: 0.917205
  width: 640
  height: 480 
# Camera frames per second
  fps: 30.0 
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
  RGB: 1 

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor:
# ORB Extractor: Number of features per image
  nFeatures: 1000          
# ORB Extractor: Scale factor between levels in the scale pyramid      
  scaleFactor: 1.2 
# ORB Extractor: Number of levels in the scale pyramid
  nLevels: 8  
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
  iniThFAST: 20
  minThFAST: 7

#--------------------------------------------------------------------------------------------
# NeRF Parameters
#--------------------------------------------------------------------------------------------
NeRF:
  aabb_scale: 4
  scale: 0.33
  offset: [0.5, 0.5, -0.1]
  network_config_path: "./Thirdparty/instant-ngp-kf/configs/nerf/base.json"