%YAML 1.2
---
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera:
  fx: 1810.6
  fy: 809.51
  cx: 955.27
  cy: 539.26
  k1: 0.130536
  k2: -0.282798
  p1: 0.000192367
  p2: 0.000213751
  k3: 0
  width: 1920
  height: 1080
# Camera frames per second
  fps: 30.0 
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
  RGB: 1 

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor:
# ORB Extractor: Number of features per image
  nFeatures: 2000      
# ORB Extractor: Scale factor between levels in the scale pyramid      
  scaleFactor: 1.2 
# ORB Extractor: Number of levels in the scale pyramid
  nLevels: 8  
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
  iniThFAST: 20
  minThFAST: 7

#--------------------------------------------------------------------------------------------
# NeRF Parameters
#--------------------------------------------------------------------------------------------
NeRF:
  aabb_scale: 2
  scale: 0.15
  offset: [0.5, 0.5, 0.4]
  network_config_path: "./Thirdparty/instant-ngp-kf/configs/nerf/base.json"